name: Tests
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  test:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        include:
        - ruby: 2.2.10
          gemfile: Gemfile
        - ruby: 2.3.8
          gemfile: Gemfile
        - ruby: 2.4.10
          gemfile: Gemfile
        - ruby: 2.5.8
          gemfile: Gemfile
        - ruby: 2.6.6
          gemfile: Gemfile
        - ruby: 2.7.2
          gemfile: Gemfile
        - ruby: 3.0.0
          gemfile: Gemfile
    env:
      BUNDLE_GEMFILE: "${{ matrix.gemfile }}"
    steps:
    - uses: actions/checkout@v2
    - name: Install ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "${{ matrix.ruby }}"
    - name: Bundle
      run: |
        gem install bundler:1.17.3
        bundle install --no-deployment
    - name: Install VNC viewer
      run: |
        sudo apt-get update
        sudo apt-get install -y xtightvncviewer
    - name: Run tests
      run: bundle exec rake
    
